import type { StorageData } from '@/types'

const DAY = 24 * 60 * 60 * 1000

export const SEED_DATA: StorageData = {
  version: 1,
  folders: [
    { id: 'f1', name: 'Work', isPinned: true, isExpanded: true, createdAt: Date.now() - 30 * DAY },
    { id: 'f2', name: 'Personal', isPinned: false, isExpanded: true, createdAt: Date.now() - 20 * DAY },
    { id: 'f3', name: 'Reading List', isPinned: false, isExpanded: true, createdAt: Date.now() - 10 * DAY },
  ],
  notes: [
    {
      id: 'n1',
      title: 'Q2 Goals',
      content: 'Q2 Goals\nLaunch redesigned sidebar\nImprove load time by 30%\nWrite onboarding docs',
      color: 'blue',
      folderId: 'f1',
      isPinned: true,
      createdAt: Date.now() - 14 * DAY,
      updatedAt: Date.now() - 1 * DAY,
    },
    {
      id: 'n2',
      title: 'Meeting Notes',
      content: 'Meeting Notes\nDiscussed rollout plan\nNext check-in Thursday\nAction: send recap email',
      color: 'yellow',
      folderId: 'f1',
      isPinned: false,
      createdAt: Date.now() - 7 * DAY,
      updatedAt: Date.now() - 3 * DAY,
    },
    {
      id: 'n3',
      title: 'Bug Backlog',
      content: 'Bug Backlog\nContext menu z-index on Linux\nDrag ghost flicker in Firefox\nSearch not clearing on folder switch',
      color: 'rose',
      folderId: 'f1',
      isPinned: false,
      createdAt: Date.now() - 5 * DAY,
      updatedAt: Date.now() - 5 * DAY,
    },
    {
      id: 'n4',
      title: 'Grocery List',
      content: 'Grocery List\nOats, almond milk\nSpinach, cherry tomatoes\nDark chocolate',
      color: 'green',
      folderId: 'f2',
      isPinned: false,
      createdAt: Date.now() - 2 * DAY,
      updatedAt: Date.now() - 2 * DAY,
    },
    {
      id: 'n5',
      title: 'Weekend Ideas',
      content: 'Weekend Ideas\nHike at the reservoir\nTry the new ramen place\nFinish the bookshelf build',
      color: 'orange',
      folderId: 'f2',
      isPinned: false,
      createdAt: Date.now() - 4 * DAY,
      updatedAt: Date.now() - 4 * DAY,
    },
    {
      id: 'n6',
      title: '',
      content: 'Pick up dry cleaning before 6pm',
      color: 'pink',
      folderId: 'f2',
      isPinned: false,
      createdAt: Date.now() - 1 * DAY,
      updatedAt: Date.now() - 1 * DAY,
    },
    {
      id: 'n7',
      title: 'Atomic Habits',
      content: 'Atomic Habits\nBy James Clear\n"You do not rise to the level of your goals, you fall to the level of your systems."',
      color: 'purple',
      folderId: 'f3',
      isPinned: true,
      createdAt: Date.now() - 10 * DAY,
      updatedAt: Date.now() - 6 * DAY,
    },
    {
      id: 'n8',
      title: 'Deep Work',
      content: 'Deep Work\nCal Newport\nSchedule focus blocks in the morning\nTurn off notifications',
      color: 'teal',
      folderId: 'f3',
      isPinned: false,
      createdAt: Date.now() - 8 * DAY,
      updatedAt: Date.now() - 8 * DAY,
    },
    {
      id: 'n9',
      title: 'Release checklist',
      content: 'Release checklist\nBump version in package.json\nTag commit\nUpdate changelog\nPost in #releases',
      color: 'slate',
      folderId: null,
      isPinned: true,
      createdAt: Date.now() - 20 * DAY,
      updatedAt: Date.now() - 2 * DAY,
    },
    {
      id: 'n10',
      title: '',
      content: 'Try Tailwind v4 on the next project',
      color: 'white',
      folderId: null,
      isPinned: false,
      createdAt: Date.now() - 3 * DAY,
      updatedAt: Date.now() - 3 * DAY,
    },
  ],
  prefs: {
    sortBy: 'updated',
    sortDir: 'desc',
    layoutMode: 'grid',
    lastView: 'all',
  },
}
